"A particular intergalactic location available for booking"
type Listing {
  id: ID!
  title: String!
  "The listing's description"
  description: String!
  numOfBeds: Int
  costPerNight: Float
  closedForBookings: Boolean
  "Amenities available at this listing"
  amenities: [Amenity!]!
}
